export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_GET_REQUEST_SUCCESS = "AUTH_GET_REQUEST_SUCCESS";
export const AUTH_REQUEST_FAILURE = "AUTH_REQUEST_FAILURE";
export const REGISTER_SUCCESS_REQUEST = "REGISTER_SUCCESS_REQUEST";







