import React from 'react'

function Admin() {
  return (
    <div>
      Added new Admin page...
    </div>
  )
}
// Added a dummy comment...
// Added second dummy comment...
// Added third dummy comment...
// Added Fourth dummy comment...
export default Admin
